### ISSUE TITLE
Enable deleting verbs

### ISSUE THREAD

**Issue by clavery63** [clavery63/point-click#50]
Currently, you can create Verbs in admin for items and scenery. You can also create and delete individual VerbLogics. However, you cannot delete a Verb once you create it. We need to add a delete button for entire verbs. I'm thinking it can be a trash can icon next to the verb name:

<img width="638" alt="Screen Shot 2022-03-19 at 1 29 04 PM" src="https://user-images.githubusercontent.com/4368490/159131917-23402059-478a-44a7-9e13-8fb7761ddae2.png">

1. For starters, make sure you have the latest master branch: `git pull`
2. Then create a new branch for this work: `git checkout -b doug/delete-verbs` or `gco -b doug/delete-verbs` if the first one doesn't work
3. Take a look at the root component for that Verbs section. Specifically, look at the how `handleChange` is defined. We hopefully should be able to call that function without changing anything about its function body: https://github.com/clavery63/point-click/blob/master/src/admin/ui/verbs/index.tsx#L19
4. Instead, we should update the function argument types to make `verbLogics` optional. so `verbLogics: VerbLogic[]` would become `verbLogics?: VerbLogic[]`.
5. Then, we're going to have to update the reducer. Specifically, we need to make the VerbLogics optional there as well: https://github.com/clavery63/point-click/blob/master/src/admin/store/reducers/gameStateReducer/worldStateReducer/entitiesReducer.ts#L34. (becomes `verbLogics?: VerbLogic[]`). Now, if we call `handleChange` without `verbLogics`, it will come in as `undefined`, which should erase it from the mapping in the game store (and hence delete it)
6. Notice that the `handleChange` function gets passed to `VerbList`. Open that file and look at how the verb name is displayed: https://github.com/clavery63/point-click/blob/master/src/admin/ui/verbs/VerbList.tsx#L39. We are going to want to display a trash can next to that. Here is an example of where that icon is being used already: https://github.com/clavery63/point-click/blob/master/src/admin/ui/rooms/ListRooms.tsx#L54
7. Notice how handleChange is typically being called with two arguments in `VerbList` (e.g. `handleChange(verbIndex, newVerbLogics);`). Since we made the second argument optional, we want to call it with just one argument. This should happen in the `onClick` handler of your `IconButton` (look the ListRooms example for how that's done). This onClick should do nothing but called `handleChange` with `verbIndex`
8. And then push up your changes to github: `git push -u origin doug/delete-verbs`

And that should be it. To debug, you can try putting a `debugger` statement in the setEntityVerb function to see what's getting passed in (`verbLogics` should be `undefined`): https://github.com/clavery63/point-click/blob/master/src/admin/store/reducers/gameStateReducer/worldStateReducer/entitiesReducer.ts#L113

**Comment by dbleek** [comment]
I have everything compiling correctly, but it seems like passing in `verbLogics ` as `undefined ` causes the page to go blank. In the dev tools, the error message mentions the call to `verbLogics.map` in  `VerbList` cannot read `undefined` (line 42). It seems like there should be a way to filter verbs that have been deleted to prevent calling `map` on them, but I couldn't figure it out.

**Comment by clavery63** [comment]
Oh shoot, sounds like I was wrong about the behavior of just setting value as `undefined`. I thought that by setting `verbLogics` as `undefined`, it would signal to the browser that the corresponding entry in that mapping no longer existed, and just get cleaned up (referring to this line: https://github.com/clavery63/point-click/blob/master/src/admin/store/reducers/gameStateReducer/worldStateReducer/entitiesReducer.ts#L117)

However, clearly the `undefined` value is sticking around and causing issues, so I guess you'll have to explicitly delete it. After line 118 in that file, it would be:

```javascript
if (!verbLogics) {
  delete newVerbs[verbIndex];
}
```

**Comment by clavery63** [comment]
See if that works (you can also put a debugger right after that line to confirm there isn't an `undefined` value sitting around. And then you might put a `debugger` in `verbs/index.tsx` to make sure we aren't about to render a `VerbList` with an `undefined` value.

I think at this point I might make a separate reducer action entirely for it, but there might be a few too many moving parts to make that a reasonable task for you right now. Maybe once you get this working, I'll do that as a followup to show you what would go into that.

Essentially the idea would just be to have a separate function entirely that does the `delete` (maybe `deleteEntityVerb`), rather than giving `setEntityVerb` dual responsibility)

**Comment by dbleek** [comment]
Explicitly deleting the verbs in `setEntityVerb` works and there are no lingering verbs in `newVerbs` after the deletion. The changes are pushed if you would like to use them in the meanwhile until we can make a new reducer for deletion.

**Comment by clavery63** [comment]
Awesome, so even for relatively small changes when working with someone, I like to make a pull request. Can you try doing that for your branch? In the top bar (on this page for instance), click Pull Requests. Then on the upper right of that page, click New Pull Request. That should take you to a page like the one I screenshot where you can search for your branch as the "compare" branch and then create it:
<img width="1786" alt="Screen Shot 2022-03-20 at 3 35 13 PM" src="https://user-images.githubusercontent.com/4368490/159179637-3ea89b4a-c79f-4ffb-b7db-6897cd2cea60.png">
